# Form implementation generated from reading ui file 'LoginWindow.ui'
#
# Created by: PyQt6 UI code generator 6.6.1
#
# WARNING: Any manual changes made to this file will be lost when pyuic6 is
# run again.  Do not edit this file unless you know what you are doing.


from PyQt6 import QtCore, QtGui, QtWidgets


class Ui_LoginWindow(object):
    def setupUi(self, LoginWindow):
        LoginWindow.setObjectName("LoginWindow")
        LoginWindow.resize(400, 300)
        self.centralwidget = QtWidgets.QWidget(parent=LoginWindow)
        self.centralwidget.setObjectName("centralwidget")
        self.verticalLayout = QtWidgets.QVBoxLayout(self.centralwidget)
        self.verticalLayout.setObjectName("verticalLayout")
        spacerItem = QtWidgets.QSpacerItem(20, 40, QtWidgets.QSizePolicy.Policy.Minimum, QtWidgets.QSizePolicy.Policy.Expanding)
        self.verticalLayout.addItem(spacerItem)
        self.lblTitle = QtWidgets.QLabel(parent=self.centralwidget)
        self.lblTitle.setStyleSheet("font-size: 18px; font-weight: bold; color: #2c3e50;")
        self.lblTitle.setAlignment(QtCore.Qt.AlignmentFlag.AlignCenter)
        self.lblTitle.setObjectName("lblTitle")
        self.verticalLayout.addWidget(self.lblTitle)
        spacerItem1 = QtWidgets.QSpacerItem(20, 20, QtWidgets.QSizePolicy.Policy.Minimum, QtWidgets.QSizePolicy.Policy.Expanding)
        self.verticalLayout.addItem(spacerItem1)
        self.formLayout = QtWidgets.QFormLayout()
        self.formLayout.setObjectName("formLayout")
        self.lblUsername = QtWidgets.QLabel(parent=self.centralwidget)
        self.lblUsername.setObjectName("lblUsername")
        self.formLayout.setWidget(0, QtWidgets.QFormLayout.ItemRole.LabelRole, self.lblUsername)
        self.txtUsername = QtWidgets.QLineEdit(parent=self.centralwidget)
        self.txtUsername.setObjectName("txtUsername")
        self.formLayout.setWidget(0, QtWidgets.QFormLayout.ItemRole.FieldRole, self.txtUsername)
        self.lblPassword = QtWidgets.QLabel(parent=self.centralwidget)
        self.lblPassword.setObjectName("lblPassword")
        self.formLayout.setWidget(1, QtWidgets.QFormLayout.ItemRole.LabelRole, self.lblPassword)
        self.txtPassword = QtWidgets.QLineEdit(parent=self.centralwidget)
        self.txtPassword.setEchoMode(QtWidgets.QLineEdit.EchoMode.Password)
        self.txtPassword.setObjectName("txtPassword")
        self.formLayout.setWidget(1, QtWidgets.QFormLayout.ItemRole.FieldRole, self.txtPassword)
        self.verticalLayout.addLayout(self.formLayout)
        self.btnLogin = QtWidgets.QPushButton(parent=self.centralwidget)
        self.btnLogin.setStyleSheet("QPushButton { \n"
"  background-color: #3498db; \n"
"  color: white; \n"
"  padding: 10px; \n"
"  border-radius: 5px;\n"
"  font-size: 14px;\n"
"  font-weight: bold;\n"
"}\n"
"QPushButton:hover {\n"
"  background-color: #2980b9;\n"
"}")
        self.btnLogin.setObjectName("btnLogin")
        self.verticalLayout.addWidget(self.btnLogin)
        self.lblStatus = QtWidgets.QLabel(parent=self.centralwidget)
        self.lblStatus.setStyleSheet("color: red; font-size: 12px;")
        self.lblStatus.setText("")
        self.lblStatus.setAlignment(QtCore.Qt.AlignmentFlag.AlignCenter)
        self.lblStatus.setObjectName("lblStatus")
        self.verticalLayout.addWidget(self.lblStatus)
        spacerItem2 = QtWidgets.QSpacerItem(20, 40, QtWidgets.QSizePolicy.Policy.Minimum, QtWidgets.QSizePolicy.Policy.Expanding)
        self.verticalLayout.addItem(spacerItem2)
        LoginWindow.setCentralWidget(self.centralwidget)

        self.retranslateUi(LoginWindow)
        QtCore.QMetaObject.connectSlotsByName(LoginWindow)

    def retranslateUi(self, LoginWindow):
        _translate = QtCore.QCoreApplication.translate
        LoginWindow.setWindowTitle(_translate("LoginWindow", "Đăng Nhập - Credit Risk System"))
        self.lblTitle.setText(_translate("LoginWindow", "CREDIT RISK SCORING SYSTEM"))
        self.lblUsername.setText(_translate("LoginWindow", "Tên đăng nhập:"))
        self.txtUsername.setPlaceholderText(_translate("LoginWindow", "Nhập username"))
        self.lblPassword.setText(_translate("LoginWindow", "Mật khẩu:"))
        self.txtPassword.setPlaceholderText(_translate("LoginWindow", "Nhập mật khẩu"))
        self.btnLogin.setText(_translate("LoginWindow", "Đăng Nhập"))
