# Form implementation generated from reading ui file 'MainWindow.ui'
#
# Created by: PyQt6 UI code generator 6.6.1
#
# WARNING: Any manual changes made to this file will be lost when pyuic6 is
# run again.  Do not edit this file unless you know what you are doing.


from PyQt6 import QtCore, QtGui, QtWidgets


class Ui_MainWindow(object):
    def setupUi(self, MainWindow):
        MainWindow.setObjectName("MainWindow")
        MainWindow.resize(1200, 800)
        self.centralwidget = QtWidgets.QWidget(parent=MainWindow)
        self.centralwidget.setObjectName("centralwidget")
        self.verticalLayout = QtWidgets.QVBoxLayout(self.centralwidget)
        self.verticalLayout.setObjectName("verticalLayout")
        self.headerLayout = QtWidgets.QHBoxLayout()
        self.headerLayout.setObjectName("headerLayout")
        self.lblWelcome = QtWidgets.QLabel(parent=self.centralwidget)
        self.lblWelcome.setStyleSheet("font-size: 14px; font-weight: bold;")
        self.lblWelcome.setObjectName("lblWelcome")
        self.headerLayout.addWidget(self.lblWelcome)
        spacerItem = QtWidgets.QSpacerItem(40, 20, QtWidgets.QSizePolicy.Policy.Expanding, QtWidgets.QSizePolicy.Policy.Minimum)
        self.headerLayout.addItem(spacerItem)
        self.btnLogout = QtWidgets.QPushButton(parent=self.centralwidget)
        self.btnLogout.setStyleSheet("QPushButton {\n"
"  background-color: #e74c3c;\n"
"  color: white;\n"
"  padding: 8px 15px;\n"
"  border-radius: 4px;\n"
"  font-weight: bold;\n"
"}\n"
"QPushButton:hover {\n"
"  background-color: #c0392b;\n"
"}")
        self.btnLogout.setObjectName("btnLogout")
        self.headerLayout.addWidget(self.btnLogout)
        self.verticalLayout.addLayout(self.headerLayout)
        self.tabWidget = QtWidgets.QTabWidget(parent=self.centralwidget)
        self.tabWidget.setObjectName("tabWidget")
        self.tabPrediction = QtWidgets.QWidget()
        self.tabPrediction.setObjectName("tabPrediction")
        self.tabWidget.addTab(self.tabPrediction, "")
        self.tabDashboard = QtWidgets.QWidget()
        self.tabDashboard.setObjectName("tabDashboard")
        self.tabWidget.addTab(self.tabDashboard, "")
        self.verticalLayout.addWidget(self.tabWidget)
        MainWindow.setCentralWidget(self.centralwidget)
        self.menubar = QtWidgets.QMenuBar(parent=MainWindow)
        self.menubar.setGeometry(QtCore.QRect(0, 0, 1200, 21))
        self.menubar.setObjectName("menubar")
        MainWindow.setMenuBar(self.menubar)
        self.statusbar = QtWidgets.QStatusBar(parent=MainWindow)
        self.statusbar.setObjectName("statusbar")
        MainWindow.setStatusBar(self.statusbar)

        self.retranslateUi(MainWindow)
        self.tabWidget.setCurrentIndex(0)
        QtCore.QMetaObject.connectSlotsByName(MainWindow)

    def retranslateUi(self, MainWindow):
        _translate = QtCore.QCoreApplication.translate
        MainWindow.setWindowTitle(_translate("MainWindow", "Credit Risk Scoring System"))
        self.lblWelcome.setText(_translate("MainWindow", "Xin chào, User"))
        self.btnLogout.setText(_translate("MainWindow", "Đăng Xuất"))
        self.tabWidget.setTabText(self.tabWidget.indexOf(self.tabPrediction), _translate("MainWindow", "Dự Báo Rủi Ro"))
        self.tabWidget.setTabText(self.tabWidget.indexOf(self.tabDashboard), _translate("MainWindow", "Dashboard"))
